plugins {
	id'java-library'
	id'maven-publish'
	id'net.neoforged.gradle.userdev' version '7.0.192'
	id'org.jetbrains.kotlin.jvm'
}

jarJar.enable()

tasks.named('wrapper', Wrapper).configure {
	// Define wrapper values here so as to not have to always do so when updating gradlew.properties.
	// Switching this to Wrapper.DistributionType.ALL will download the full gradle sources that comes with
	// documentation attached on cursor hover of gradle classes and methods. However, this comes with increased
	// file size for Gradle. If you do switch this to ALL, run the Gradle wrapper task twice afterwards.
	// (Verify by checking gradle/wrapper/gradle-wrapper.properties to see if distributionUrl now points to `-all`)
	distributionType = Wrapper.DistributionType.ALL
}

configurations {
	provided
	compile.extendsFrom(provided)
}

repositories {
	exclusiveContent {
		forRepository {
			maven {
				url = "https://cursemaven.com"
			}
		}
		filter {
			includeGroup "curse.maven"
		}
	}
	mavenCentral()
}

base {
	archivesName = mod_id
}


// Mojang ships Java 21 to end users in 1.21, so mods should target Java 21.

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
	withSourcesJar()
	withJavadocJar()
}

runs {
	configureEach {
		systemProperty 'forge.logging.markers', 'REGISTRIES'
		systemProperty 'forge.logging.console.level', 'debug'
		modSource project.sourceSets.main
	}

	data {
		arguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
	}
}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }

tasks {
	compileJava {
		options.encoding = "UTF-8"
	}

	javadoc {
		options.encoding = "UTF-8"
	}

	build {
//		dependsOn(shadowJar)
	}

//	shadowJar {
//		val mapping = mapOf("de.chojo.sadu" to "sadu")
//		val base = "dev.chojo.myplugin.libs."
//		for ((pattern, name) in mapping) relocate(pattern, "${base}${name}")
//	}
}


dependencies {
	implementation "net.neoforged:neoforge:${neo_version}"
	implementation "curse.maven:selene-499980:6818413"
	implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"

	implementation "party.iroiro.luajava:luajava:4.0.2"
	provided "party.iroiro.luajava:luajava:4.0.2"
	implementation'party.iroiro.luajava:lua54:4.0.2'
	provided 'party.iroiro.luajava:lua54:4.0.2'
	implementation'party.iroiro.luajava:lua54-platform:4.0.2:natives-desktop'
	provided 'party.iroiro.luajava:lua54-platform:4.0.2:natives-desktop'
}

var dissonancePath = "C:/Users/Chymic/AppData/Roaming/PrismLauncher/instances/dissonance 2.5 dev 121 update/minecraft/mods"
var jarFileName = "${base.archivesName.get()}.jar"



jar {
	doNotTrackState "aaaaa FFRHHj"
	project.logger.lifecycle "MACHINE WITNESS - $jarFileName"
	// Include all of the jars from the bundled configuration in our jar
	from configurations.provided.asFileTree.files.collect { zipTree(it) }
}

tasks.register("mjajrjrjfFUCK") {
	it.doNotTrackState "god it just always needs to be copied you FUCK"
	copy {
		from("build/libs/$jarFileName")
		into dissonancePath
	}
}

tasks.withType(ProcessResources).configureEach {
	var replaceProperties = [
		minecraft_version      : minecraft_version,
		minecraft_version_range: minecraft_version_range,
		neo_version            : neo_version,
		loader_version_range   : loader_version_range,
		mod_id                 : mod_id,
		mod_name               : mod_name,
		mod_license            : mod_license,
		mod_version            : mod_version,
		mod_authors            : mod_authors,
		mod_description        : mod_description
	]
	inputs.properties replaceProperties

	filesMatching(['META-INF/neoforge.mods.toml']) {
		expand replaceProperties
	}
}

//tasks.withType(JavaCompile).configureEach {
//	options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
//}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
	module {
		downloadSources = true
		downloadJavadoc = true
	}
}

kotlin {
	jvmToolchain(21)
}


